config/routes.rb
Rails.application.routes.draw do
  resources :grades
  root 'grades#index'
  

end

app/models/grade.rb
class Grade < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:Mark, :MarkOutOf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Mark %><br>
    <%= f.text_field :Mark %>
  </div>
  <div class="field">
    <%= f.label :MarkOutOf %><br>
    <%= f.text_field :MarkOutOf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grade Calculator</h1>
<h3>Activities</h3>

<p>Give grades to the numeric activities:</p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Short Name</th>
      <th>Grade</th>
      <th>Percentage</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td>Activity <%= grade.id %></td>
        <td>A<%= grade.id %></td>
        <td><%= grade.Mark %> / <%= grade.MarkOutOf %></td>
        <td><%= 100*grade.Mark/grade.MarkOutOf %>%</td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<thead>
      <tr>
      <th><b>TOTAL</b></th>
      <th colspan="3"></th>
    </tr>
</thead>

<br>
<br>

<button type="button" onclick="alert('IN PROGRESS')">AVERAGE</button>
<button type="button" onclick="alert('Will fix to calculate mean')">MEAN</button>

<%= link_to 'Add an Activity', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mark:</strong>
  <%= @grade.Mark %>
</p>

<p>
  <strong>Markoutof:</strong>
  <%= @grade.MarkOutOf %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalcApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>